### ISSUE TITLE
Logo for BetterPoll

### ISSUE THREAD

**Issue by adityabisht02** [adityabisht02/Betterpoll#3]
Create a logo for this application , you can do so using figma or whatever tool u are comfortable in.

**Comment by TBUGOP** [comment]
Please assign this to me.

**Comment by adityabisht02** [comment]
go ahead umang :)

**Comment by TBUGOP** [comment]
[https://www.figma.com/file/mEZSWJvuUZDB3L3GIgR3q5/Betterpoll-Logo](url)
Check This.

**Comment by adityabisht02** [comment]
Looks cool!
